site_name: SMX 0225

theme:
  name: material
  language: es

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest
    - content.code.copy
    - toc.follow

  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Modo oscuro

    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Modo claro

extra_css:
  - assets/css/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 2

extra_javascript:
  - assets/js/marcadores.js